# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{systeminformation}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Maier"]
  s.date = %q{2010-06-07}
  s.description = %q{Provides information about cpu, memory, network throughput, current load and usercount}
  s.email = %q{stefanmaier@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/systeminformation.rb",
     "lib/systeminformation/linux/cpu.rb",
     "lib/systeminformation/linux/load.rb",
     "lib/systeminformation/linux/memory.rb",
     "lib/systeminformation/linux/net.rb",
     "lib/systeminformation/os.rb",
     "lib/systeminformation/unix/users.rb",
     "systeminformation.gemspec"
  ]
  s.homepage = %q{http://github.com/tliff/systeminformation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provides information about the system}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

